routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Auth\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ScheduleMessageController;
use App\Http\Controllers\AssignCreditController;
use App\Http\Controllers\ApiDeliveryReportController;
use App\Http\Controllers\APISmsController;
use App\Http\Controllers\AuditlogsController;
use App\Http\Controllers\MoSmsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/smsapi', [APISmsController::class,'sms_api']);

Route::get('/usercharts',[DashboardController::class,'user_charts']);
Route::get('/apitokensmtn',[DashboardController::class,'tokens_mtn']);
Route::get('/apitokensairtel',[DashboardController::class,'tokens_airtel']);

Route::get('/dlr',[DashboardController::class,'bulksmsdeliveryreports']);
    
Route::get('/api_dlr',[DashboardController::class,'apideliveryreports']);

Route::middleware('auth')->group(function() {

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('logout', [AuthController::class, 'logout'])->name('logout'); 
});

Route::middleware('loggedin')->group(function() {
    Route::get('login', [AuthController::class, 'loginView'])->name('login-view');
    Route::post('login', [AuthController::class, 'login'])->name('login');
    
    
    //Route::get('register', [AuthController::class, 'registerView'])->name('register-view');
    //Route::post('register', [AuthController::class, 'register'])->name('register');
});

Route::resource('roles', RoleController::class);

Route::resource('permissions', PermissionsController::class);
// Route::resource('roles', RoleController::class);
// Route::resource('permissions', PermissionsController::class);

/**
 * User Routes
 */
Route::group(['prefix' => 'users'], function() {
    Route::get('/', [UserController::class ,'index'])->name('users.index');
    Route::get('/create', [UserController::class ,'create'])->name('users.create');
    Route::post('/create', [UserController::class ,'store'])->name('users.store');
    Route::get('/{user}/show', [UserController::class ,'show'])->name('users.show');
    Route::get('/{user}/edit', [UserController::class ,'edit'])->name('users.edit');
    Route::post('/{user}/update', [UserController::class ,'update'])->name('users.update');
    Route::get('/{user}/delete', [UserController::class ,'destroy'])->name('users.destroy');
    Route::get('/units', [UserController::class ,'units'])->name('users.units');
    
});

Route::get('/users', [UserController::class ,'index'])->name('users.index')->middleware('auth');

Route::get('register', [AuthController::class, 'registerView'])->name('register-view')->middleware('auth');

Route::post('register', [AuthController::class, 'register'])->name('register')->middleware('auth');

Route::get('/audittrail', [AuditlogsController::class,'index'])->name('reports.audittrail')->middleware('auth');

Route::get('/apideliveryreports', [ApiDeliveryReportController::class,'index'])->name('reports.apideliveryreports')->middleware('auth');

Route::get('/apideliveryreportsdetailed', [ApiDeliveryReportController::class,'details'])->name('reports.apideliveryreportsdetails')->middleware('auth');

Route::post('/apideliveryreportsnumbers', [ApiDeliveryReportController::class,'numbers'])->name('reports.apideliveryreportsnumbers')->middleware('auth');

Route::get('/apideliveryreportsautocomplete', [ApiDeliveryReportController::class,'autoComplete'])->name('search.autocomplete')->middleware('auth');

Route::get('/schedulesms', [ScheduleMessageController::class,'index'])->name('broadcasts.schedulemessages')->middleware('auth');

Route::get('/assigncredit', [AssignCreditController::class,'index'])->name('credits.assigncredit')->middleware('auth');

Route::get('/export-csv2',[ApiDeliveryReportController::class,'exportCSV'])->middleware('auth')->name('reports.apideliveryreportexport')->middleware('auth');

Route::get('/export-csv4',[ApiDeliveryReportController::class,'exportCSV2'])->name('reports.apideliveryreportexportdetailed')->middleware('auth');

resources/views/layouts/partials/errors.blade.php
@if(Session::has('success') || isset($success))
    <div class="alert alert-success">{{ session('success') }}</div>
@elseif(Session::has('status'))
    <div class="alert alert-success">{{ session('status') }}</div>
@elseif(Session::has('info'))
    <div class="alert alert-info">{{ Session::get('info') }}</div>
@endif

@if($errors->count() > 0)

@php
    $error_list = '';
    foreach ($errors->all() as $error) {
        $error_list .= $error.'<br>';
    }
@endphp
    @php
        $message = $error_list;
        $type = 'danger';
    @endphp
    <div class="alert alert-{{ $type }}">{!! $message !!}</div>
@endif 

resources/views/layouts/partials/messages.blade.php
@if(Session::get('success', false))
    <?php $data = Session::get('success'); ?>
    @if (is_array($data))
        @foreach ($data as $msg)
            <div class="alert alert-success" role="alert">
                <i class="fa fa-check"></i>
                {{ $msg }}
            </div>
        @endforeach
    @else
        <div class="alert alert-success" role="alert">
            <i class="fa fa-check"></i>
            {{ $data }}
        </div>
    @endif
@endif

resources/views/layouts/partials/navbar.blade.php
<!-- BEGIN: Breadcrumb -->
<div class="-intro-x breadcrumb mr-auto hidden sm:flex"> <a href="" class="">Application</a> <i data-feather="chevron-right" class="breadcrumb__icon"></i> <a href="" class="breadcrumb--active">Dashboard</a> </div>
<!-- END: Breadcrumb -->
<!-- BEGIN: Search 
<div class="intro-x relative mr-3 sm:mr-6">
   <div class="search hidden sm:block">
      <input type="text" class="search__input input placeholder-theme-13" placeholder="Search...">
      <i data-feather="search" class="search__icon dark:text-gray-300"></i> 
   </div>
   <a class="notification sm:hidden" href=""> <i data-feather="search" class="notification__icon dark:text-gray-300"></i> </a>
   <div class="search-result">

   </div>
</div>
END: Search -->

<!-- BEGIN: Account Menu -->
<div class="intro-x dropdown w-8 h-8">
   <div class="dropdown-toggle w-8 h-8 rounded-full overflow-hidden shadow-lg image-fit zoom-in">
      <img alt="Midone Tailwind HTML Admin Template" src={{asset("dist/images/profile-1.jpg")}}>
   </div>
   <div class="dropdown-box w-56">
      <div class="dropdown-box__content box bg-theme-38 dark:bg-dark-6 text-white">
         <div class="p-4 border-b border-theme-40 dark:border-dark-3">
            <div class="font-medium">{{ $user = auth()->user()->name;}}</div>
            <!--<div class="text-xs text-theme-41 dark:text-gray-600">DevOps Engineer</div>-->
         </div>
         
         <div class="p-2 border-t border-theme-40 dark:border-dark-3">
            <a href="{{ route('logout') }}" class="flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-1 dark:hover:bg-dark-3 rounded-md"> <i data-feather="toggle-right" class="w-4 h-4 mr-2"></i> Logout </a>
         </div>
      </div>
   </div>
</div>
<!-- END: Account Menu -->

resources/views/layouts/partials/sidebar.blade.php
<nav class="side-nav">
   <a href="" class="intro-x flex items-center pl-5 pt-4">
   <img alt="Midone Tailwind HTML Admin Template" class="w-6" src="{{ asset('dist/images/dlight_logo.svg') }}">
   <span class="hidden xl:block text-white text-lg ml-3"> d.light<span class="font-medium">Uganda</span> </span>
   </a>
   <div class="side-nav__devider my-6"></div>
   <ul>
      <li>
         <a href="{{ route('dashboard') }}" class="side-menu side-menu--active">
            <div class="side-menu__icon"> <i data-feather="home"></i> </div>
            <div class="side-menu__title"> Dashboard </div>
         </a>
      </li>
      @can('admin.menu')
      <li class="side-nav__devider my-6"></li>
      <li>
         <a href="javascript:;" class="side-menu">
            <div class="side-menu__icon"> <i data-feather="settings"></i> </div>
            <div class="side-menu__title"> Admin Panel <i data-feather="chevron-down" class="side-menu__sub-icon"></i> </div>
         </a>
         <ul class="">
            <li>
               <a href="{{ route('users.index') }}" class="side-menu">
                  <div class="side-menu__icon"> <i data-feather="arrow-right"></i> </div>
                  <div class="side-menu__title"> View Users </div>
               </a>
            </li>
            <li>
               <a href="{{ route('roles.index') }}" class="side-menu">
                  <div class="side-menu__icon"> <i data-feather="arrow-right"></i> </div>
                  <div class="side-menu__title"> Manage Roles </div>
               </a>
            </li>
            <li>
               <a href="{{ route('permissions.index') }}" class="side-menu">
                  <div class="side-menu__icon"> <i data-feather="arrow-right"></i> </div>
                  <div class="side-menu__title"> Permissions </div>
               </a>
            </li>
            <li>
               <a href="{{ route('register') }}" class="side-menu ? 'active' : ''">
                  <div class="side-menu__icon"> <i data-feather="arrow-right"></i> </div>
                  <div class="side-menu__title"> Add Users </div>
               </a>
            </li>
         </ul>
      </li>  
      @endcan    
      <div class="side-nav__devider my-6"></div> 
      <li>
         <a href="javascript:;" class="side-menu">
            <div class="side-menu__icon"> <i data-feather="trending-up"></i> </div>
            <div class="side-menu__title"> Reports <i data-feather="chevron-down" class="side-menu__sub-icon"></i> </div>
         </a>
         <ul class="">
            <li>
               <a href="{{ route('reports.apideliveryreports') }}" class="side-menu">
                  <div class="side-menu__icon"> <i data-feather="arrow-right"></i> </div>
                  <div class="side-menu__title"> API Delivery Reports </div>
               </a>
            </li>
            <li>
               <a href="{{ route('reports.apideliveryreportsdetails') }}" class="side-menu">
                  <div class="side-menu__icon"> <i data-feather="arrow-right"></i> </div>
                  <div class="side-menu__title"> API Delivery Reports Details</div>
               </a>
            </li>
         </ul>
      </li>     
   </ul>
</nav>