routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Auth\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ScheduleMessageController;
use App\Http\Controllers\AssignCreditController;
use App\Http\Controllers\ApiDeliveryReportController;
use App\Http\Controllers\APISmsController;
use App\Http\Controllers\AuditlogsController;
use App\Http\Controllers\MoSmsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/smsapi', [APISmsController::class,'sms_api']);

Route::get('/usercharts',[DashboardController::class,'user_charts']);
Route::get('/apitokensmtn',[DashboardController::class,'tokens_mtn']);
Route::get('/apitokensairtel',[DashboardController::class,'tokens_airtel']);

Route::get('/dlr',[DashboardController::class,'bulksmsdeliveryreports']);
    
Route::get('/api_dlr',[DashboardController::class,'apideliveryreports']);

Route::middleware('auth')->group(function() {

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('logout', [AuthController::class, 'logout'])->name('logout'); 
});

Route::middleware('loggedin')->group(function() {
    Route::get('login', [AuthController::class, 'loginView'])->name('login-view');
    Route::post('login', [AuthController::class, 'login'])->name('login');
    
    
    //Route::get('register', [AuthController::class, 'registerView'])->name('register-view');
    //Route::post('register', [AuthController::class, 'register'])->name('register');
});

Route::resource('roles', RoleController::class);

Route::resource('permissions', PermissionsController::class);
// Route::resource('roles', RoleController::class);
// Route::resource('permissions', PermissionsController::class);

/**
 * User Routes
 */
Route::group(['prefix' => 'users'], function() {
    Route::get('/', [UserController::class ,'index'])->name('users.index');
    Route::get('/create', [UserController::class ,'create'])->name('users.create');
    Route::post('/create', [UserController::class ,'store'])->name('users.store');
    Route::get('/{user}/show', [UserController::class ,'show'])->name('users.show');
    Route::get('/{user}/edit', [UserController::class ,'edit'])->name('users.edit');
    Route::post('/{user}/update', [UserController::class ,'update'])->name('users.update');
    Route::get('/{user}/delete', [UserController::class ,'destroy'])->name('users.destroy');
    Route::get('/units', [UserController::class ,'units'])->name('users.units');
    
});

Route::get('/users', [UserController::class ,'index'])->name('users.index')->middleware('auth');

Route::get('register', [AuthController::class, 'registerView'])->name('register-view')->middleware('auth');

Route::post('register', [AuthController::class, 'register'])->name('register')->middleware('auth');

Route::get('/audittrail', [AuditlogsController::class,'index'])->name('reports.audittrail')->middleware('auth');

Route::get('/apideliveryreports', [ApiDeliveryReportController::class,'index'])->name('reports.apideliveryreports')->middleware('auth');

Route::get('/apideliveryreportsdetailed', [ApiDeliveryReportController::class,'details'])->name('reports.apideliveryreportsdetails')->middleware('auth');

Route::post('/apideliveryreportsnumbers', [ApiDeliveryReportController::class,'numbers'])->name('reports.apideliveryreportsnumbers')->middleware('auth');

Route::get('/apideliveryreportsautocomplete', [ApiDeliveryReportController::class,'autoComplete'])->name('search.autocomplete')->middleware('auth');

Route::get('/schedulesms', [ScheduleMessageController::class,'index'])->name('broadcasts.schedulemessages')->middleware('auth');

Route::get('/assigncredit', [AssignCreditController::class,'index'])->name('credits.assigncredit')->middleware('auth');

Route::get('/export-csv2',[ApiDeliveryReportController::class,'exportCSV'])->middleware('auth')->name('reports.apideliveryreportexport')->middleware('auth');

Route::get('/export-csv4',[ApiDeliveryReportController::class,'exportCSV2'])->name('reports.apideliveryreportexportdetailed')->middleware('auth');

app/Http/Controllers/PermissionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;

class PermissionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $permissions = Permission::all();

        return view('permissions.index', [
            'permissions' => $permissions
        ]);
    }
    public function show()
    {   
        $permissions = Permission::all();

        return view('permissions.index', [
            'permissions' => $permissions
        ]);
    }

    /**
     * Show form for creating permissions
     * 
     * @return \Illuminate\Http\Response
     */
    public function create() 
    {   
        return view('permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $request->validate([
            'name' => 'required|unique:users,name'
        ]);

        Permission::create($request->only('name'));

        return redirect()->route('permissions.index')
            ->withSuccess(__('Permission created successfully.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Permission  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        return view('permissions.edit', [
            'permission' => $permission
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $request->validate([
            'name' => 'required|unique:permissions,name,'.$permission->id
        ]);

        $permission->update($request->only('name'));

        return redirect()->route('permissions.index')
            ->withSuccess(__('Permission updated successfully.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();

        return redirect()->route('permissions.index')
            ->withSuccess(__('Permission deleted successfully.'));
    }
}

resources/views/permissions/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="intro-y col-span-12 lg:col-span-6">
     <div class="intro-y box"> 
         <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                Add new permission 
            </h2>
         </div>
        <div class="intro-y box p-5">

            <form method="POST" action="{{ route('permissions.store') }}">
                @csrf
                <div class="mt-3">  
                    <label>Name</label>
                    <input value="{{ old('name') }}" type="text" class="input w-full rounded-full border mt-2" name="name" placeholder="Name" required>

                    @if ($errors->has('name'))
                        <span class="text-danger text-left">{{ $errors->first('name') }}</span>
                    @endif
                </div>
                <div class="text-right mt-5">
                    <button type="submit" class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white">Save</button>
                    <a href="{{ route('permissions.index') }}" ><button type="button" class="button w-24 rounded-full shadow-md mr-1 mb-2 text-gray-700 dark:bg-dark-5 dark:text-gray-300">Back</button></a>
                </div>
            </form>
        </div>
    </div>    
</div>
@endsection

resources/views/permissions/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="intro-y col-span-12 lg:col-span-6">
    <div class="intro-y box"> 
         <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                    Edit permission 
            </h2>
         </div>      
         <div class="intro-y box p-5">
            <form method="POST" action="{{ route('permissions.update', $permission->id) }}">
                @method('patch')
                @csrf
                <div class="mt-3">
                    <label>Name</label>
                    <input value="{{ $permission->name }}" type="text" class="input w-full rounded-full border mt-2" name="name" placeholder="Name" required>

                    @if ($errors->has('name'))
                        <span class="text-danger text-left">{{ $errors->first('name') }}</span>
                    @endif
                </div>
                <div class="text-right mt-5">
                    <button type="submit" class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white">Save</button>
                    <a href="{{ route('permissions.index') }}"><button type="button" class="button w-24 rounded-full shadow-md mr-1 mb-2 text-gray-700 dark:bg-dark-5 dark:text-gray-300">Back</button></a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/permissions/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="intro-y col-span-12 lg:col-span-12">
	<div class="intro-y box">
		<div class="mt-2">
            @include('layouts.partials.messages')
        </div>
		<div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
			<h2>Permissions</h2>
		</div>
		<div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
			<a href="{{ route('permissions.create') }}" class="btn btn-primary btn-sm float-left">
				<button class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white">Add</button>
			</a>
		</div>
		<div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200" id="head-options-table">
			<div class="preview">
				<div class="overflow-x-auto">
					<table class="table">
						<thead>
							<tr class="bg-gray-200 text-gray-700">
								<th class="whitespace-no-wrap">Name</th>
								<th class="whitespace-no-wrap">Guard</th>
								<th class="whitespace-no-wrap" colspan="2"></th>
							</tr>
						</thead>
						<tbody>
                @foreach($permissions as $permission)
                    
							<tr>
								<td class="whitespace-no-wrap">{{ $permission->name }}</td>
								<td class="whitespace-no-wrap">{{ $permission->guard_name }}</td>
								<td class="whitespace-no-wrap">
									<a class="flex items-center mr-3" href="{{ route('permissions.edit', $permission->id) }}">
										<i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit 
									</a>
								</td>
								<td class="whitespace-no-wrap" scope="row">
									<div class="flex justify-center items-center">

										<a class="flex items-center text-theme-6" href="{{ route('permissions.destroy', $permission->id) }}">
											<i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete 
										</a>
									</div>
								</td>
							</tr>
                @endforeach
            
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection