routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Auth\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ScheduleMessageController;
use App\Http\Controllers\AssignCreditController;
use App\Http\Controllers\ApiDeliveryReportController;
use App\Http\Controllers\APISmsController;
use App\Http\Controllers\AuditlogsController;
use App\Http\Controllers\MoSmsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/smsapi', [APISmsController::class,'sms_api']);

Route::get('/usercharts',[DashboardController::class,'user_charts']);
Route::get('/apitokensmtn',[DashboardController::class,'tokens_mtn']);
Route::get('/apitokensairtel',[DashboardController::class,'tokens_airtel']);

Route::get('/dlr',[DashboardController::class,'bulksmsdeliveryreports']);
    
Route::get('/api_dlr',[DashboardController::class,'apideliveryreports']);

Route::middleware('auth')->group(function() {

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('logout', [AuthController::class, 'logout'])->name('logout'); 
});

Route::middleware('loggedin')->group(function() {
    Route::get('login', [AuthController::class, 'loginView'])->name('login-view');
    Route::post('login', [AuthController::class, 'login'])->name('login');
    
    
    //Route::get('register', [AuthController::class, 'registerView'])->name('register-view');
    //Route::post('register', [AuthController::class, 'register'])->name('register');
});

Route::resource('roles', RoleController::class);

Route::resource('permissions', PermissionsController::class);
// Route::resource('roles', RoleController::class);
// Route::resource('permissions', PermissionsController::class);

/**
 * User Routes
 */
Route::group(['prefix' => 'users'], function() {
    Route::get('/', [UserController::class ,'index'])->name('users.index');
    Route::get('/create', [UserController::class ,'create'])->name('users.create');
    Route::post('/create', [UserController::class ,'store'])->name('users.store');
    Route::get('/{user}/show', [UserController::class ,'show'])->name('users.show');
    Route::get('/{user}/edit', [UserController::class ,'edit'])->name('users.edit');
    Route::post('/{user}/update', [UserController::class ,'update'])->name('users.update');
    Route::get('/{user}/delete', [UserController::class ,'destroy'])->name('users.destroy');
    Route::get('/units', [UserController::class ,'units'])->name('users.units');
    
});

Route::get('/users', [UserController::class ,'index'])->name('users.index')->middleware('auth');

Route::get('register', [AuthController::class, 'registerView'])->name('register-view')->middleware('auth');

Route::post('register', [AuthController::class, 'register'])->name('register')->middleware('auth');

Route::get('/audittrail', [AuditlogsController::class,'index'])->name('reports.audittrail')->middleware('auth');

Route::get('/apideliveryreports', [ApiDeliveryReportController::class,'index'])->name('reports.apideliveryreports')->middleware('auth');

Route::get('/apideliveryreportsdetailed', [ApiDeliveryReportController::class,'details'])->name('reports.apideliveryreportsdetails')->middleware('auth');

Route::post('/apideliveryreportsnumbers', [ApiDeliveryReportController::class,'numbers'])->name('reports.apideliveryreportsnumbers')->middleware('auth');

Route::get('/apideliveryreportsautocomplete', [ApiDeliveryReportController::class,'autoComplete'])->name('search.autocomplete')->middleware('auth');

Route::get('/schedulesms', [ScheduleMessageController::class,'index'])->name('broadcasts.schedulemessages')->middleware('auth');

Route::get('/assigncredit', [AssignCreditController::class,'index'])->name('credits.assigncredit')->middleware('auth');

Route::get('/export-csv2',[ApiDeliveryReportController::class,'exportCSV'])->middleware('auth')->name('reports.apideliveryreportexport')->middleware('auth');

Route::get('/export-csv4',[ApiDeliveryReportController::class,'exportCSV2'])->name('reports.apideliveryreportexportdetailed')->middleware('auth');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get();
        return view('roles.create',compact('permissions'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
    
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
    
        return view('roles.show',compact('role','rolePermissions'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
    
        return view('roles.edit',compact('role','permission','rolePermissions'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
    
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('roles.index')
                        ->with('success','Role deleted successfully');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="intro-y col-span-12 lg:col-span-6">
  <div class="intro-y box">  
    <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
        <h2 class="font-medium text-base mr-auto">      
           Add new role 
        </h2>
    </div>  
        
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
            </ul>
        </div>
    @endif
    <div class="intro-y box p-5">     
    <form method="POST" action="{{ route('roles.store') }}">
    @csrf
    <div class="mt-3">
        <div class="col-lg-3">
            <label>Name:</label>
            <input value="{{ old('name') }}"  type="text"  class="input w-full rounded-full border mt-2 col-span-2" name="name" placeholder="Role Name" required>
        </div>
    </div>
    <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200" id="head-options-table">
		<div class="preview">
            <div class="overflow-x-auto">
                <table class="table">
                <thead>
                    <th class="bg-gray-200 text-gray-700"><input type="checkbox" name="all_permission"></th>
                    <th class="bg-gray-200 text-gray-700">Name</th>
                    <th class="bg-gray-200 text-gray-700">Guard</th> 
                </thead>

                    @foreach($permissions as $permission)
                        <tr>
                            <td class="border-b dark:border-dark-5">
                                <input type="checkbox" 
                                name="permission[{{ $permission->name }}]"
                                value="{{ $permission->name }}"
                                >
                            </td>
                            <td class="border-b dark:border-dark-5">{{ $permission->name }}</td>
                            <td class="border-b dark:border-dark-5">{{ $permission->guard_name }}</td>
                        </tr>
                    @endforeach
                </table>
             </div>
           </div>
          </div>
          <div class="text-right mt-5">
            <button type="submit" class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white">Save user</button>
            <a href="{{ route('users.index') }}"><button type="button" class="button w-24 rounded-full shadow-md mr-1 mb-2 text-gray-700 dark:bg-dark-5 dark:text-gray-300">Back</button></a>
-         </div>
        </form>
     </div>
  </div>
</div>  
@endsection
@section('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $('[name="all_permission"]').on('click', function() {

            if($(this).is(':checked')) {
                $.each($('.permission'), function() {
                    $(this).prop('checked',true);
                });
            } else {
                $.each($('.permission'), function() {
                    $(this).prop('checked',false);
                });
            }
            
        });
    });
</script>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="intro-y col-span-12 lg:col-span-6">
	<div class="intro-y box">
          <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
                   <h2 class="font-medium text-base mr-auto">    
                       Update role
                    </h2>
            </div>
                    <div class="intro-y box p-5">
                        Edit role and manage permissions.
                    </div>
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="intro-y box p-5">
                        <form method="POST" action="{{ route('roles.update', $role->id) }}">
                            @method('patch')
                            @csrf
                            <div class="mt-3"> 
                              <div class="col-lg-3">
                                <label>Name</label>
                                <input value="{{ $role->name }}" type="text" class="input w-full rounded-full border mt-2" name="name" placeholder="Name" required>
                              </div>
                            </div>
                            <div class="mt-3"> 
                                <div class="col-lg-3">
                                    <label>Assign Permissions</label>
                                </div>
                            </div>
                        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200" id="head-options-table">
		                   <div class="preview">
                              <div class="overflow-x-auto">
                            <table class="table">
                                <thead>
                                    <th class="bg-gray-200 text-gray-700"><input type="checkbox" name="all_permission"></th>
                                    <th class="bg-gray-200 text-gray-700">Name</th>
                                    <th class="bg-gray-200 text-gray-700">Guard</th>
                                </thead>

                                @foreach ($permission as $permission)
                                    <tr>
                                        <td class="border-b dark:border-dark-5">
                                            <input type="checkbox" name="permission[{{ $permission->name }}]"
                                                value="{{ $permission->name }}" class='permission'
                                                {{ in_array($permission->name, $rolePermissions) ? 'checked' : '' }}>
                                        </td>
                                        <td class="border-b dark:border-dark-5">{{ $permission->name }}</td>
                                        <td class="border-b dark:border-dark-5">{{ $permission->guard_name }}</td>
                                    </tr>
                                @endforeach
                            </table>
                            </div>
                            </div>
                            </div>
                            <div class="text-left mt-5">
                              <button type="submit" class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white">Save</button>
                              <a href="{{ route('roles.index') }}" class="btn btn-default"><button type="button" class="button w-24 rounded-full shadow-md mr-1 mb-2 text-gray-700 dark:bg-dark-5 dark:text-gray-300">Back</button></a>
                            </div>
                        </form>
                    </div>
                  </div>
                </div>

              </div>
            </div>
            @endsection

            @section('scripts')
                <script type="text/javascript">
                    $(document).ready(function() {
                        $('[name="all_permission"]').on('click', function() {

                            if ($(this).is(':checked')) {
                                $.each($('.permission'), function() {
                                    $(this).prop('checked', true);
                                });
                            } else {
                                $.each($('.permission'), function() {
                                    $(this).prop('checked', false);
                                });
                            }

                        });
                    });
                </script>
            @endsection

resources/views/roles/index.blade.php
@extends('../layouts.admin')

@section('content')
<div class="intro-y col-span-12 lg:col-span-12">
	<div class="intro-y box">
        <div class="mt-2">
            @include('../layouts.partials.messages')
        </div>
       
        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
           <h2>Roles</h2>
        </div>
        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
            <a href="{{ route('roles.create') }}" class="btn btn-primary btn-sm float-right"><button class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white">Add role</button></a>
        </div>
        
        
        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200" id="head-options-table">
			<div class="preview">
				<div class="overflow-x-auto">
        <table class="table">
          <tr class="bg-gray-200 text-gray-700">
             <th class="whitespace-no-wrap">No</th>
             <th class="whitespace-no-wrap">Name</th>
             <th class="whitespace-no-wrap" colspan="3">Action</th>
          </tr>
            @foreach ($roles as $key => $role)
            <tr>
                <td class="whitespace-no-wrap">{{ $role->id }}</td>
                <td class="whitespace-no-wrap">{{ $role->name }}</td>
                <td class="whitespace-no-wrap">
                    <a class="btn btn-info btn-sm" href="{{ route('roles.show', $role->id) }}"><button class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-9 text-white">Show</button></a>
                </td>
                <td class="whitespace-no-wrap">
                    <a  href="{{ route('roles.edit', $role->id) }}"><button class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-12 text-white">Edit</button></a>
                </td>
                <td class="whitespace-no-wrap">
                   <a  href="{{ route('roles.destroy', $role->id) }}"><button class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-6 text-white">Delete</button></a>      
                </td>
            </tr>
            @endforeach
        </table>

        <div class="d-flex">
            {!! $roles->links() !!}
        </div>

        </div>
      
   
</div>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="intro-y col-span-12 lg:col-span-6">
    <div class="intro-y box">
            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
                <h2 class="font-medium text-base mr-auto">      
                   {{ ucfirst($role->name) }} Roles
                </h2>
            </div>
            <div class="intro-y box p-5">

                <h3>Assigned permissions</h3>

                <table class="table">
                    <thead>
                        <th class="bg-gray-200 text-gray-700">Name</th>
                        <th class="bg-gray-200 text-gray-700">Guard</th>
                    </thead>

                    @foreach ($rolePermissions as $permission)
                        <tr>
                            <td class="border-b dark:border-dark-5">{{ $permission->name }}</td>
                            <td class="border-b dark:border-dark-5">{{ $permission->guard_name }}</td>
                        </tr>
                    @endforeach
                </table>
                <div class="mt-4">
                    <a href="{{ route('roles.edit', $role->id) }}" ><button class="button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-1 text-white" type="submit">Edit</button></a>
                    <a href="{{ route('roles.index') }}" ><button class="button w-24 rounded-full shadow-md mr-1 mb-2 text-gray-700 dark:bg-dark-5 dark:text-gray-300" type="button">Back</button></a>
                </div>
            </div>             
    </div>
</div>
    @endsection